-- Minimal teams table used by the app to know which Nevobo team codes exist.
--
-- Run this in Supabase SQL Editor (only if you don't already have a `public.teams` table).
-- After creating it, add ALL your teams (Table Editor or INSERT statements).

create table if not exists public.teams (
  team_id bigint generated by default as identity primary key,
  -- Store either a code ("HS1", "JB1") OR a readable name ("Heren 2", "Jongens B 1").
  -- The app will derive a code from this string.
  team_name text not null unique
);

alter table public.teams enable row level security;

drop policy if exists "teams_select_all_authenticated" on public.teams;
create policy "teams_select_all_authenticated"
on public.teams
for select
to authenticated
using (true);

-- Optional: allow only admins to manage teams (adjust if you have different admin logic).
drop policy if exists "teams_manage_admins" on public.teams;
create policy "teams_manage_admins"
on public.teams
for all
to authenticated
using (coalesce(public.is_global_admin(), false) is true)
with check (coalesce(public.is_global_admin(), false) is true);

